### ISSUE TITLE
incorrect key assignment in user preferences

### ISSUE THREAD

**Issue by pieper** [OHIF/react-viewerbase#13]
On my keyboard (US English on a mac book pro) some basic keys work to define shortcust, like numbers and letters, but other keys result in the wrong characters.  For example the equals key results in a double right chevron, and the minus key gives the symbol for one half.

![image](https://user-images.githubusercontent.com/126077/50832101-2bb77980-131b-11e9-90d9-8cd36255b4f2.png)

**Comment by maltempi** [comment]
Thanks @pieper , I just reproduced this bug here, I'll take this as soon as possible! 

Abraço!

**Comment by pieper** [comment]
Thanks! 👍
