### ISSUE TITLE
script tag usage through npm/unpkg

### ISSUE THREAD

**Issue by pieper** [OHIF/react-viewerbase#22]
Do we have an example using react-viewerbase via a script tag?  Is it supported?

**Comment by pieper** [comment]
@galelis do you know how to add building umd and publishing it to npm?  @swederik showed me where it goes and it doesn't look too hard.

**Comment by galelis** [comment]
I haven't done this using rollup, but should be easy. I will keep you posted.

**Comment by swederik** [comment]
Looks like this should be possible now with https://github.com/OHIF/react-viewerbase/pull/27, we just have to publish a new version.

**Comment by pieper** [comment]
awesome!  @swederik can you publish?

**Comment by swederik** [comment]
Sure, published 0.2.3 and now it should work. Here's an example page:

https://gist.github.com/swederik/7e29d70167708dce5ebde8d85d55bb73

**Comment by pieper** [comment]
Cool - that works - thanks guys!
