### ISSUE TITLE
is there any chance to get this working with vuejs too?

### ISSUE THREAD

**Issue by miconx** [OHIF/react-viewerbase#24]

**Comment by swederik** [comment]
We could look into wrapping each component into a Custom Element which could be dropped into Vue or any other view layer library. I'd be happy to take a PR if it worked. Maybe something like this: https://github.com/bspaulding/react-custom-element

**Comment by dannyrb** [comment]
@miconx, while these components could serve as inspiration for a similar Vue component library, it is not currently on our road map to create one. If you choose to spearhead the effort, please be sure to let us know! I would be more than happy to add a reference/link to a maintained and well-featured Vue repo.
