### ISSUE TITLE
How to get complete code run

### ISSUE THREAD

**Issue by deligence** [OHIF/react-viewerbase#34]
I want to implement complete code with all components when I import and uses this is says it is an object expected a single component

import  CornerstoneViewport from 'react-viewerbase'

<CornerstoneViewport />

How to implement complete ohif running code in my react app ?

**Comment by swederik** [comment]
This is only one set of components, not the whole viewer. We plan to release the whole viewer as a package as well `ohif-viewer`, but it's not quite ready yet. You can see the progress on this branch: https://github.com/OHIF/Viewers/tree/react/

Specifically, the package in question is:

https://github.com/OHIF/Viewers/tree/react/Packages-react/ohif-viewer

You can try following index.html inside this example folder:
https://github.com/OHIF/Viewers/tree/react/Packages-react/ohif-viewer/example

Note that this stuff is still under development, so we make no promises about not breaking everything on a daily basis.
