### ISSUE TITLE
rollup does not start website

### ISSUE THREAD

**Issue by EsrefDurna** [OHIF/react-viewerbase#35]
environment
OS - ubuntu 16.04  64bit
node version v11.9.0
npm version 6.7.0

**$git clone https://github.com/OHIF/react-viewerbase
$cd react-viewerbase/
$yarn install
$yarn start**

rollup v0.68.2
bundles src/index.js → dist/index.js, dist/index.es.js...

and rollup watches files,  If i change a file it recompiled
Problem
I visit http://localhost:3000/ nothing is there.
This site can’t be reached

FYI create-react-app works fine,

**Comment by swederik** [comment]
Rollup is not meant to start a website. Rollup just builds the library. There is an 'example' folder which uses the library to run a website. See https://github.com/OHIF/react-viewerbase/blob/master/README.md#to-run-locally
