### ISSUE TITLE
How do I use this package as a local dependency for another project?

### ISSUE THREAD

**Issue by yaoli** [OHIF/react-viewerbase#43]
I've noticed this package is used in other places such as OHIF viewer in here: https://github.com/OHIF/Viewers/tree/react/Packages-react. I've started to modify `react-viewerbase` locally and see its effect in `ohif-viewer`. As the external dependency, I've used `yarn link react-viewerbase` and OHIF viewer appears to be able to link to it. 

The problem is with debugging both projects at the same time. While I'm able to set debugging breakpoints in `ohif-viewer/src`, setting breakpoints in `react-viewerbase/src` does not work when launching the `ohif-viewer`. My intuition tells me that the source maps of the external (and local) dependencies are not built by default as `yarn link` creates a symbolic link under `ohif-viewer/node_modules`. I haven't been able to solve this problem after googling for a few days (few people seem to have this issue after all, which makes me think there are other alternative ways to accomplish it), and wonder if you would have some good suggestions. Thank you in advance and any help is much appreciated.

**Comment by swederik** [comment]
Yeah this is something we have been struggling with as well. I've been using yalc (https://github.com/whitecolor/yalc) instead of yarn link since there are a bunch of dependencies in ohif-viewer that are shared amongst packages (e.g. ohif-cornerstone-extension depends on ohif-core, dcmjs, cornerstone, etc, and so does ohif-viewer).

**Comment by yaoli** [comment]
Thanks for the prompt response. I've taken a look at `yalc`, without trying though, I'm not sure it addresses the issue of unable to set debug breakpoints across packages/local dependencies. @swederik Could you comment on this particularly?

More edit, I've tried `yalc`, and set up a debug point in '.yalc/src', which doesn't get acknowledged. So the question remains.

**Comment by dannyrb** [comment]
@yaoli, a potential approach is to develop the two in isolation. I'm working on a pull request that creates a playground for each component from source. You can write tests or provide different data sets to the components in their playgrounds. Ideally, you should be able to "unit test" the components for the different scenarios you expect and see/play with the output.

This should at least reduce the need of "end to end" testing for a vertical slice of development.

Probably not the answer you were looking for -- If you do stumble upon an elegant solution, be sure to let us know ^_^
