### ISSUE TITLE
Example Dependency Error

### ISSUE THREAD

**Issue by FMCalisto** [OHIF/react-viewerbase#5]
When following your [README](https://github.com/OHIF/react-viewerbase/blob/master/README.md) sample, I stuck into an installation problem. The output of the error is as follows.

1. By doing the dependency installation inside your `example/` folder, like you said, we have this:
```
> npm install
```

2. Then, the output of the errors are:

```
npm ERR! path /Users/Francisco/Git/react-viewerbase/example/node_modules/.staging/react-viewerbase-091ed109/node_modules/@babel/code-frame
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/Users/Francisco/Git/react-viewerbase/example/node_modules/.staging/react-viewerbase-091ed109/node_modules/@babel/code-frame' -> '/Users/Francisco/Git/react-viewerbase/example/node_modules/.staging/@babel/code-frame-275380b3'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Francisco/.npm/_logs/2018-12-13T14_34_35_435Z-debug.log
```

Anyway, I also would like to congratualte your effort, by giving us, the community, a [React](https://react.ohif.org/) version. Thank you!

**Comment by swederik** [comment]
Use yarn instead of npm and it should work fine. 

See https://npm.community/t/npm-install-for-package-with-local-dependency-fails/754

**Comment by pieper** [comment]
@FMCalisto what version of the README were you looking at?  The current one (the one you linked) says to use yarn...

**Comment by FMCalisto** [comment]
Sorry for the mismatch information from my side. Already run the source by using `yarn` build. Not sure if it was also a [NodeJS](https://nodejs.org) error since I need to update and then reinstall [NodeJS](https://nodejs.org) from the first time I ran with `yarn`. But nevermind, now everything is working fine.

Again, thank you for your contributions. Your work is of chief importance to me and to my work team. Congratulations for your great work here with [OHIF](https://github.com/OHIF).

**Comment by pieper** [comment]
Thank you!  And thanks for following up,
