### ISSUE TITLE
Component "props" should render beneath playground

### ISSUE THREAD

**Issue by dannyrb** [OHIF/react-viewerbase#67]
We want props for components to load like this:

![image](https://user-images.githubusercontent.com/5797588/56161412-72121980-5f97-11e9-814f-133c9a722a50.png)

In version 1, they do not. We need to watch this issue for a fix:

https://github.com/pedronauck/docz/issues/777

**Comment by dannyrb** [comment]
This issue appears to be resolved for all components except for Icons. Check out:

![image](https://user-images.githubusercontent.com/5797588/59433841-53be7380-8db8-11e9-8536-7fea2b3c3ee5.png)

**Comment by swederik** [comment]
This is also broken for the Study List: https://react.ohif.org/components/study-list
